# Generated by Django 5.2.7 on 2025-11-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_bank_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='national_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='National ID/Passport'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tin',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='TIN'),
        ),
    ]
