# inventory/urls.py

from rest_framework.routers import DefaultRouter
from django.urls import path, include
from .views import InventoryPartViewSet, CategoryViewSet, VendorViewSet

# Create a router instance
router = DefaultRouter()

# Register ViewSets with the router
# The base path for all these will be /api/inventory/ 
router.register(r'parts', InventoryPartViewSet, basename='part')
router.register(r'categories', CategoryViewSet, basename='category')
router.register(r'vendors', VendorViewSet, basename='vendor')

urlpatterns = [
    # Include all URLs generated by the router
    # e.g., /api/inventory/parts/, /api/inventory/categories/{id}/
    path('', include(router.urls)),
]