# clients/urls.py (MODIFIED)

from rest_framework.routers import DefaultRouter
from django.urls import path, include
# 🔑 REMOVED: DashboardMetricsView import is no longer needed here
from .views import ClientViewSet, VehicleViewSet 

# Create a router instance
router = DefaultRouter()

# Register ViewSets with the router
router.register(r'', ClientViewSet, basename='client')
router.register(r'vehicles', VehicleViewSet, basename='vehicle')


urlpatterns = [
    # 🛑 REMOVED: The path('dashboard/metrics/', ...) line is removed!
    
    # Include all URLs generated by the router
    path('', include(router.urls)),
]