# clients/urls.py

from rest_framework_nested import routers # 🛑 Use rest_framework_nested routers
from django.urls import path, include

from .views import ClientViewSet, VehicleViewSet 

# --- Setup for Client/Vehicle Nested Routing ---

# 1. Create a DefaultRouter for the primary resource (Client)
router = routers.DefaultRouter()

# Register the Client ViewSet
# This registers: 
#   /api/clients/          (LIST, CREATE)
#   /api/clients/{id}/     (RETRIEVE, UPDATE, DESTROY)
#   /api/clients/export/   (Custom 'export' action)
router.register(r'', ClientViewSet, basename='client')

# 2. Create a nested router for the secondary resource (Vehicle)
# Vehicles belong to a specific client: /api/clients/{client_pk}/vehicles/
clients_router = routers.NestedDefaultRouter(router, r'', lookup='client')

# Register the Vehicle ViewSet under the client endpoint
# The basename is now 'client-vehicles'
clients_router.register(r'vehicles', VehicleViewSet, basename='client-vehicles')


urlpatterns = [
    # Include all URLs generated by the default router (clients/)
    path('', include(router.urls)),
    # 🛑 Include all URLs generated by the nested router (clients/{id}/vehicles/)
    path('', include(clients_router.urls)),
]