# clients/urls.py

from rest_framework.routers import DefaultRouter
from django.urls import path, include
from .views import ClientViewSet, VehicleViewSet

# Create a router instance
router = DefaultRouter()

# Register ViewSets with the router
# This generates URLs like:
# /clients/ (GET, POST)
# /clients/{id}/ (GET, PUT, DELETE)
router.register(r'', ClientViewSet, basename='client')

# Vehicles are registered separately.
# This generates URLs like:
# /vehicles/ (POST) - to create
# /vehicles/{id}/ (GET, PUT, DELETE)
# NOTE: We use 'vehicles' here to distinguish it from the client base path
router.register(r'vehicles', VehicleViewSet, basename='vehicle')


urlpatterns = [
    # Include all URLs generated by the router
    # These will be prefixed by the master router path '/api/clients/'
    path('', include(router.urls)),
]