# Generated by Django 5.2.7 on 2025-11-06 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+255xxxxxxxxx'. It must start with +255 and include at least one digit.", regex='^\\+255\\d+$')]),
        ),
    ]
