# Generated by Django 5.2.7 on 2025-11-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Commercial', 'Commercial')], default='Individual', max_length=20, verbose_name='Client Type'),
        ),
    ]
