# Generated by Django 5.2.7 on 2025-11-07 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_client_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, help_text='Any important notes, preferences, or history about the client.', null=True, verbose_name='Client Notes'),
        ),
        migrations.AddField(
            model_name='client',
            name='tax_id',
            field=models.CharField(blank=True, help_text='Tax identification number (e.g., VAT, TIN, or Business ID).', max_length=50, null=True, verbose_name='Tax/VAT ID'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Company', 'Company')], default='Individual', max_length=20, verbose_name='Client Type'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+255xxxxxxxxx'. It must start with +255 and be 10 to 16 digits long.", regex='^\\+255\\d{9,15}$')]),
        ),
    ]
