# Generated by Django 5.2.7 on 2025-11-07 07:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_notes_client_tax_id_alter_client_client_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid international format. The local number part must be exactly 9 digits long and cannot start with zero.', regex='^\\+?\\d{1,4}[1-9]\\d{8}$')]),
        ),
    ]
