# Generated by Django 5.2.7 on 2025-11-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_client_options_client_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='apply_discount',
            field=models.BooleanField(default=False, help_text='If checked, the default discount (5%) is applied to invoices.', verbose_name='Apply Default Discount'),
        ),
        migrations.AddField(
            model_name='client',
            name='custom_labor_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Override Labor Rate ($)'),
        ),
        migrations.AddField(
            model_name='client',
            name='custom_markup_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Override Markup (%)'),
        ),
        migrations.AddField(
            model_name='client',
            name='custom_payment_terms',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Override Terms (e.g., 'Net 45')"),
        ),
        migrations.AddField(
            model_name='client',
            name='is_tax_exempt',
            field=models.BooleanField(default=False, help_text="If activated, no taxes (VAT) will be added to this client's invoices.", verbose_name='Tax Exempt'),
        ),
        migrations.AddField(
            model_name='client',
            name='labor_rate_override',
            field=models.BooleanField(default=False, help_text='Enables a specific labor rate override for this client.', verbose_name='Custom Labor Rate'),
        ),
        migrations.AddField(
            model_name='client',
            name='parts_markup_override',
            field=models.BooleanField(default=False, help_text='Enables a specific parts markup percentage override for this client.', verbose_name='Custom Parts Markup'),
        ),
        migrations.AddField(
            model_name='client',
            name='payment_terms_override',
            field=models.BooleanField(default=False, help_text="Enables specific payment terms for this client's invoices.", verbose_name='Custom Payment Terms'),
        ),
    ]
