# Generated by Django 5.2.7 on 2025-11-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_alter_client_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='odometer',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Exterior Color'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='drivetrain',
            field=models.CharField(blank=True, choices=[('FWD', 'Front-Wheel Drive (FWD)'), ('RWD', 'Rear-Wheel Drive (RWD)'), ('AWD', 'All-Wheel Drive (AWD)'), ('4x4/4WD', '4x4 / Four-Wheel Drive (4WD)')], max_length=20, null=True, verbose_name='Drivetrain'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine',
            field=models.CharField(blank=True, help_text='e.g., 2.0L Turbo, V6, Electric, etc.', max_length=100, null=True, verbose_name='Engine Type'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='notes',
            field=models.TextField(blank=True, help_text='Any important notes about the vehicle', null=True, verbose_name='Vehicle Notes'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='odo_reading',
            field=models.CharField(blank=True, help_text='Current mileage/kilometers/hours', max_length=100, null=True, verbose_name='Odometer Reading'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='odo_unit',
            field=models.CharField(choices=[('miles', 'Miles'), ('kilometers', 'Kilometers'), ('hours', 'Hours')], default='miles', max_length=20, verbose_name='Odometer Unit'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(blank=True, help_text='e.g., Automatic, Manual, CVT, etc.', max_length=100, null=True, verbose_name='Transmission Type'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='trim',
            field=models.CharField(blank=True, help_text='e.g., Base, Sport, Luxury, etc.', max_length=100, null=True, verbose_name='Trim Level'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='unit_number',
            field=models.CharField(blank=True, help_text='Internal identification number for the vehicle', max_length=50, null=True, verbose_name='Internal Unit Number'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(blank=True, help_text='e.g., Sedan, SUV, Truck, etc.', max_length=100, null=True, verbose_name='Vehicle Type'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='License Plate'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(blank=True, help_text='Vehicle Identification Number', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
