# Generated by Django 5.2.7 on 2025-10-19 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open/In Progress'), ('INSPECT', 'Inspection/Diagnosis'), ('PENDING_APPROVAL', 'Pending Client Approval'), ('CLOSED', 'Completed & Invoiced'), ('PAID', 'Paid'), ('CANCELED', 'Canceled')], default='DRAFT', max_length=20)),
                ('date_in', models.DateTimeField(auto_now_add=True)),
                ('date_promised', models.DateTimeField(blank=True, null=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('initial_odometer', models.IntegerField(help_text='Odometer reading at job start')),
                ('parts_subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('labor_subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('assigned_technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_cards', to='clients.client')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_cards', to='clients.vehicle')),
            ],
            options={
                'verbose_name': 'Job Card',
                'verbose_name_plural': 'Job Cards',
                'ordering': ['-date_in'],
            },
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('PART', 'Part'), ('LABOR', 'Labor'), ('FEE', 'Fee/Miscellaneous')], max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('labor_time_hrs', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('line_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='jobcards.jobcard')),
            ],
            options={
                'ordering': ['date_added'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Credit/Debit Card'), ('TRANSFER', 'Bank Transfer'), ('OTHER', 'Other')], max_length=20)),
                ('date_paid', models.DateTimeField(auto_now_add=True)),
                ('transaction_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='jobcards.jobcard')),
            ],
            options={
                'ordering': ['date_paid'],
            },
        ),
    ]
