# employees/urls.py

from django.urls import path, include
from rest_framework.routers import DefaultRouter

# 🛑 CRITICAL: Import your EmployeeViewSet from the views.py file in this app
from .views import EmployeeViewSet 

# 1. Initialize the Router
router = DefaultRouter()

# 2. Register the Employee ViewSet
# This will handle all CRUD operations under the /api/employees/ base path.
router.register(r'', EmployeeViewSet, basename='employee')

urlpatterns = [
    # Include all URLs generated by the router (list, create, retrieve, update, delete)
    path('', include(router.urls)),
]